### PR TITLE
node changed --debug to --inspect

### PR DESCRIPTION
**Pull request by johnpapa**

### CODE REVIEW

**Comment by amarzavery** [comment]
@prashanthmadi  @cephalin - Please review and merge if everything looks good.

**Comment by johnpapa** [comment]
thanks.

let me know when we can get this merged, please.

**Comment by prashanthmadi** [comment]
I don't think we are using nodemon in production/ after deploying app to Azure. Check gulpfile.js

It would be more of for local dev purpose

**Comment by johnpapa** [comment]
Right. But it errors out now. This change will make it work locally. Hitch the docs tell people to do and now it fails.

**Comment by prashanthmadi** [comment]
@johnpapa  can you use below repo meanwhile. I will check with @cephalin  and update.
https://github.com/prashanthmadi/mean

**Comment by johnpapa** [comment]
I think that fix is fine. Maybe do that here too

https://github.com/prashanthmadi/mean/blob/master/gulpfile.js#L53

**Comment by prashanthmadi** [comment]
Yep. I was planning to push whole code in that repo to this(as that repo has recent commits of Meanjs).

**Comment by cephalin** [comment]
@prashanthmadi We are not allowed to use personal repos in our docs.

Let me know if the changes here are sufficient and I'll merge.

**Comment by prashanthmadi** [comment]
@cephalin Can you merge content from below branch.
https://github.com/prashanthmadi/mean

**Pull request closed without merging**
