### PR TITLE
add instructions to start the app

### PR DESCRIPTION
**Pull request by johnpapa**

### CODE REVIEW

**Comment by amarzavery** [comment]
@prashanthmadi  @cephalin - Please review and merge if everything looks good.

**Comment by prashanthmadi** [comment]
[Blog](https://prmadi.com/running-mean-js-app-on-azure-app-services/) referred in readme already has details for it. 
It also requires bower install.

**Comment by johnpapa** [comment]
Every sample should have quick install instructions. We shouldn't make people go elsewhere. This is something we need to make consistent on all samples.

**Comment by prashanthmadi** [comment]
@johnpapa Agreed. I will check with @cephalin  and update.
Thanks for your contribution 👍

**Pull request closed without merging**
